[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[build.nixpacksConfig]
root = "api"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 